### ISSUE TITLE
where is the TSN arkitechture?

### ISSUE THREAD

**Issue by ronghui19** [PaddlePaddle/PaddleVideo#102]

**Comment by shippingwang** [comment]
Do you mean the ```architecture```?
In our design, a recognizer model architecture is separated into two parts, backbone and heads
like TSN:
It is a recognizer2D network,
backbone is ResNet50 architecture https://github.com/PaddlePaddle/PaddleVideo/blob/develop/paddlevideo/modeling/backbones/resnet.py
and its head is tsn_head
https://github.com/PaddlePaddle/PaddleVideo/blob/develop/paddlevideo/modeling/heads/tsn_head.py

**Comment by ronghui19** [comment]
thank you
