### ISSUE TITLE
请问大规模视频分类模型Videotag模型的Accuracy, top1, top5?

### ISSUE THREAD

**Issue by dragen1860** [PaddlePaddle/PaddleVideo#104]
请问贵公司在大规模视频分类模型Videotag模型的取得了多少的Accuracy, top1, top5?

**Comment by chajchaj** [comment]
多谢关注~
我们的效果是Top-1=89.9%，Top-5=96%
如果觉得该开源项目对您有帮助，欢迎Star~

**Comment by ranjiewwen** [comment]
@chajchaj infer的时候，固定稀疏采样300帧，这个有讲究吗？如果10s左右视频，其实算很密的采样了，如果是1min视频，1s也采用了5帧左右；如果300->100效果有变化吗？测试视频长度有讲究吗，谢谢
