### ISSUE TITLE
BMN模型测试

### ISSUE THREAD

**Issue by upenggod** [PaddlePaddle/PaddleVideo#110]
“并通过METRIC.ground_truth_filename字段指定该ground_truth文件，”
请问这个METRIC.ground_truth_filename再哪里指定？

**Comment by huangjun12** [comment]
配置文件bmn.yaml里

```yaml
METRIC:
  ground_truth_filename: "data/dataset/bmn_data/activity_net_1_3_new.json"
```

**Comment by upenggod** [comment]
谢谢，看到了，但activitynet_1.3_annotations.json这个文件也没有

**Comment by huangjun12** [comment]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/22365664/106994758-60c37e00-67b8-11eb-8543-c3ea6987439a.png">

直接下载这个就行了

**Comment by huangjun12** [comment]
如果觉得该开源项目对您有帮助，欢迎Star~

**Comment by upenggod** [comment]
已经star了，但是你发的图我看不到，谢谢再次解答

**Comment by huangjun12** [comment]
activity_net_1_3_new.json文件: https://paddlemodels.bj.bcebos.com/video_detection/activity_net_1_3_new.json  
activitynet_1.3_annotations.json文件: https://paddlemodels.bj.bcebos.com/video_detection/activitynet_1.3_annotations.json

**Comment by yhl2018** [comment]
BMN怎么使用自己的一个视频片段进行测试啊？有相关教程吗？
