### ISSUE TITLE
TSM启动训练时Reader报错

### ISSUE THREAD

**Issue by SnowWhite11235** [PaddlePaddle/PaddleVideo#113]
TSM启动训练时Reader报错，麻烦帮看下可能是什么原因，谢谢！

机器：P40
docker环境：paddlepaddle/paddle:2.0.0-gpu-cuda10.1-cudnn7
/dev/shm 32G  

相关信息：
数据路径没有问题

报错如下：
Namespace(config='configs/recognition/tsm/tsm.yaml', override=[], test=False, train_dali=False, validate=True, weights=None)
build model cfg {'framework': 'Recognizer2D', 'backbone': {'name': 'ResNetTSM', 'num_seg': 8, 'depth': 50}, 'head': {'name': 'TSMHead', 'num_classes': 101, 'in_channels': 2048, 'drop_ratio': 0.5, 'std': 0.01}}
framework_type Recognizer2D
backbone {'name': 'ResNetTSM', 'num_seg': 8, 'depth': 50}
head {'name': 'TSMHead', 'num_classes': 101, 'in_channels': 2048, 'drop_ratio': 0.5, 'std': 0.01}
W0222 06:29:41.052126  2914 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1
W0222 06:29:41.057281  2914 device_context.cc:372] device: 0, cuDNN Version: 7.6.
length of train_loader:  1192
WARNING:root:DataLoader reader thread raised an exception.Traceback (most recent call last):

  File "main.py", line 73, in <module>
    main()
  File "main.py", line 69, in main
    validate=args.validate)
  File "/home/work/PaddleVideo/paddlevideo/tasks/train.py", line 117, in train_model
    for i, data in enumerate(train_loader):
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 365, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

INFO 2021-02-22 06:29:51,336 launch_utils.py:307] terminate all the procs
ERROR 2021-02-22 06:29:51,337 launch_utils.py:545] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-02-22 06:29:54,339 launch_utils.py:307] terminate all the procs

**Comment by huangjun12** [comment]
(1) dataloader的num_workers参数设成0；
(2) 清一下共享内存试试:
```bash
rm /dev/shm/* -rf
```
