### ISSUE TITLE
Kinetics400 dataset download

### ISSUE THREAD

**Issue by hoolizou** [PaddlePaddle/PaddleVideo#122]
Thank you very much for your work！
However, I met with hardship. Since I would like to train the Kinetic400 data set from beginning to end, can you provide a simpler way to download the full K400.

**Comment by chajchaj** [comment]
链接：https://pan.baidu.com/s/1S_CGBjWOUAuxL_cCX5kMPg 
提取码：ppvi

**Comment by hoolizou** [comment]
> 链接：https://pan.baidu.com/s/1S_CGBjWOUAuxL_cCX5kMPg
> 提取码：ppvi

Thank you very much!dalao
