### ISSUE TITLE
Connecting to www.crcv.ucf.edu (www.crcv.ucf.edu)|132.170.214.127|:443... failed: Connection refused.

### ISSUE THREAD

**Issue by hhh5446** [PaddlePaddle/PaddleVideo#128]
Connecting to www.crcv.ucf.edu (www.crcv.ucf.edu)|132.170.214.127|:443... failed: Connection refused.
ucf网址无法使用

**Comment by huangjun12** [comment]
https://www.crcv.ucf.edu/data/UCF101.php

这个进不去嘛？
