### ISSUE TITLE
关于BMN模型测试后的数据可视化的问题

### ISSUE THREAD

**Issue by ChaunceySun7** [PaddlePaddle/PaddleVideo#133]
你好，我们在对BMN模型训练后，通过所给的ActivityNet1.3得到一些csv文件以及json文件，请问csv文件中的xmin、xmax、score所代表的含义分别是什么？以及如何可以将这些结果可视化到视频上？

**Comment by huangjun12** [comment]
xmin为片段的起始时间，xmax为片段的结束时间，score为该片段对应的得分。
对训练好的模型，BMN添加了Inference功能，可参考： https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/localization/bmn.md#模型推理

可视化建议可以在视频里显示时间轴，在时间轴上对定位出的片段做一些特殊的标记
