### ISSUE TITLE
百度网盘提供的K400数据集中10s5.tar文件仅有10K，似乎有缺失

### ISSUE THREAD

**Issue by lg920810** [PaddlePaddle/PaddleVideo#143]
提供感谢PaddleVideo团队提供的Kinetics400数据集下载链接，我下载完成并解压后只有392个文件夹，应该是由于10s5.tar资源缺失导致的少了8个文件，希望您这边审查后能够补充，谢谢~

**Comment by huangjun12** [comment]
好的，我们这边check下。同时您也可以尝试脚本下载方式，https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/dataset/k400.md#%E8%84%9A%E6%9C%AC%E4%B8%8B%E8%BD%BD

**Comment by lg920810** [comment]
> 好的，我们这边check下。同时您也可以尝试脚本下载方式，https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/dataset/k400.md#%E8%84%9A%E6%9C%AC%E4%B8%8B%E8%BD%BD

好的，多谢啦~

**Comment by chajchaj** [comment]
确实有缺失，我处理下，感谢关注。

**Comment by XDLiuyyy** [comment]
您好，我也发现了该问题，使用脚本下载又不能确定是哪8类，请问您处理好了么？

非常感谢。

**Comment by lg920810** [comment]
> 您好，我也发现了该问题，使用脚本下载又不能确定是哪8类，请问您处理好了么？
> 
> 非常感谢。

我就是全部都用脚本又下载了一遍。。
