### ISSUE TITLE
BMN复现不出论文的结果

### ISSUE THREAD

**Issue by Wazxcvb** [PaddlePaddle/PaddleVideo#145]
将工程下载下来未进行任何参数的修改，数据集也是提供的链接下载的，跑出的模型测试效果特别差，AR@1-0.023、AR@5-0.088、AR@10-0.14、AR@100-0.468、Auc:32.29%,请问这个还需要调整那些参数吗，还是特征提取层需要重新编译，还是与paddle的版本有关系呢？

**Comment by huangjun12** [comment]
是develop分支嘛？Paddle版本是多少呢？ 方便贴一下你的配置文件嘛？

**Comment by Wazxcvb** [comment]
是develop分支，paddle的版本为2.0.0，python为3.6
![14kt7vxkp5r3ruq937s5orx0_0](https://user-images.githubusercontent.com/43949204/118752799-56744e00-b896-11eb-850b-dbc186eb3ec9.jpg)

**Comment by huangjun12** [comment]
原models下的代码已经不维护了，用这个repo里的代码跑吧
https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/localization/bmn.md
