### ISSUE TITLE
Kinectic400数据量不匹配

### ISSUE THREAD

**Issue by dingfengshi** [PaddlePaddle/PaddleVideo#146]
您好，百度云盘的Kinectics400数据集是不是不包含mkv的数据。但是介绍页提供的list文件里却包含了非Mp4数据。请问一下markdown里的list文件中，数据数量是不是和数据集不匹配呢？

**Comment by dingfengshi** [comment]
检查了一下, 百度云盘的数据似乎有没包含验证集的数据...

**Comment by chajchaj** [comment]
谢谢反馈，会尽快核实并补充数据。

**Comment by hhc1997** [comment]
（1）百度网盘版只有训练集 （2）训练集只有392类，少了{'crossing_river', 'cracking_neck', 'cutting_pineapple', 'crawling_baby', 'crying', 'cutting_nails', 'curling_hair', 'cutting_watermelon'}这8类

**Comment by XDLiuyyy** [comment]
您好，我也发现了该问题，使用脚本下载又不能确定是哪8类，请问您处理好了么？

非常感谢。

**Comment by hhc1997** [comment]
你好，我是把缺失的8类弄成一个新的excel，然后再用脚本下载的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleVideo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月17日(星期六) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleVideo] Kinectic400数据量不匹配 (#146)





 
您好，我也发现了该问题，使用脚本下载又不能确定是哪8类，请问您处理好了么？
 
非常感谢。
