### ISSUE TITLE
PPTSM训练问题

### ISSUE THREAD

**Issue by ShawnZhang31** [PaddlePaddle/PaddleVideo#167]
https://github.com/PaddlePaddle/PaddleVideo/tree/release/2.0, 在configs目录下找不到pptsm_football_v2.0.yaml

**Comment by huangjun12** [comment]
https://github.com/PaddlePaddle/PaddleVideo/blob/application/FootballAction/train_proposal/configs/pptsm_football_v2.0.yaml 在这里
