### ISSUE TITLE
怎么用PPTSM训练自己的数据集，一个视频有多个标签的那种

### ISSUE THREAD

**Issue by krisandchris** [PaddlePaddle/PaddleVideo#169]

**Comment by huangjun12** [comment]
1. 数据准备： 参考ucf-101数据准备过程，准备好自己的数据list文件，并相应修改dataloader支持多标签读入；
2. 多标签需要修改损失函数为 [BCEWithLogitsLoss](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/BCEWithLogitsLoss_cn.html#bcewithlogitsloss)
