### ISSUE TITLE
这个项目是不是还没有完成？

### ISSUE THREAD

**Issue by ShawnZhang31** [PaddlePaddle/PaddleVideo#173]
感觉这个文档缺了不少，总是文档和代码对不上。另外感觉在这个项目中使用依赖注入和控制反转不是太好的选择

**Comment by huangjun12** [comment]
是的，文档还需要完善升级。

项目设计上的不足烦请指出~ 以及是否有更好的设计方式参考呢？

**Comment by ShawnZhang31** [comment]
> 是的，文档还需要完善升级。
> 
> 项目设计上的不足烦请指出~ 以及是否有更好的设计方式参考呢？

其实我也没有什么好设计方式建议，就是觉得PaddleNLP的包的设计方式蛮好的，是否可以借鉴PaddleNLP的设计方式。另外提两点意见，如果有什么说的不对的地方，还请见谅：
1. 是否可以增加dataloader相关的文档，特别是自定义dataloader的文档，对于模型训练的时候的数据loader方式增加以下文档;特别是FootballAction这个app，感觉替换一下数据集用于其他的视频action检测的难度有点大
2. 是否可以将训练过程不用全部放在main.py中封装起来，是否可以借鉴PaddleNLP的方式，只是将模型组网给封装起来，对于数据的加载、优化器设置、训练过程全部让用户自己来编写，以方便将模型复用到其他的地方。

以上，是我的一点愚见，说的不对的地方，还请见谅
