### ISSUE TITLE
跑tsn的时候内存会炸，有什么办法能解决么

### ISSUE THREAD

**Issue by SpringLclin** [PaddlePaddle/PaddleVideo#178]
![image](https://user-images.githubusercontent.com/86232826/128130132-33cf9cf3-8a90-42f4-aa55-0721246f34d1.png)
这个好像打不开了

**Comment by SpringLclin** [comment]
显存也会满

**Comment by huangjun12** [comment]
> ![image](https://user-images.githubusercontent.com/86232826/128130132-33cf9cf3-8a90-42f4-aa55-0721246f34d1.png)
> 这个好像打不开了

方便贴下具体链接吗，这边看可以打开

**Comment by SpringLclin** [comment]
https://github.com/PaddlePaddle/dygraph/tsn/data/dataset/ucf101/README.md
这个里面显示not found

**Comment by huangjun12** [comment]
https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/dataset/ucf101.md ucf-101的数据说明文档在这里~
