### ISSUE TITLE
timesformer build model error

### ISSUE THREAD

**Issue by KK-Jiang** [PaddlePaddle/PaddleVideo#179]
环境： 
Ubuntu 18.04 
Paddle 2.0
Python 3.7
2*v100 32G

具体报错见：
File "main.py", line 90, in <module>
    main()
  File "main.py", line 86, in main
    amp=args.amp)
  File "xxx/PaddleVideo/paddlevideo/tasks/train.py", line 86, in train_model
    model = build_model(cfg.MODEL)
  File "xx/PaddleVideo/paddlevideo/modeling/builder.py", line 48, in build_model
    return build_recognizer(cfg)
  File "xx/PaddleVideo/paddlevideo/modeling/builder.py", line 36, in build_recognizer
    return build(cfg, RECOGNIZERS, key='framework')
  File "xx/PaddleVideo/paddlevideo/utils/build_utils.py", line 35, in build
    return obj_cls(**cfg_copy)
  File "xx/PaddleVideo/paddlevideo/modeling/framework/recognizers/base.py", line 26, in __init__
    self.backbone.init_weights()
  File "xx/PaddleVideo/paddlevideo/modeling/backbones/vit.py", line 371, in init_weights
    for m in self.blocks.sublayers(include_self=True):
TypeError: sublayers() got an unexpected keyword argument 'include_self'

**Comment by KK-Jiang** [comment]
**When I modified "for m in self.blocks.sublayers(include_self=True):" to "for m in self.blocks.sublayers():", The Error disappered but another error occured:
when loading model weight, process terminated with log info:**


Loading blocks.0.norm1.weight:
Loading blocks.0.norm1.bias:
Loading blocks.0.attn.qkv.weight:
Loading blocks.0.attn.qkv.bias:
Loading blocks.0.attn.proj.weight:
  7%|▋         | 10/150 [00:00<00:01, 97.38it/s]

Loading blocks.1.norm1.weight:
Loading blocks.1.norm1.bias:
Loading blocks.1.attn.qkv.weight:
 13%|█▎        | 20/150 [00:00<00:01, 97.61it/s]

Loading blocks.1.attn.proj.weight:
Loading blocks.1.attn.proj.bias:
Loading blocks.2.norm1.weight:
 20%|██        | 30/150 [00:00<00:01, 97.96it/s]

Loading blocks.2.attn.qkv.weight:
Loading blocks.2.attn.qkv.bias:
Loading blocks.2.attn.proj.weight:
 27%|██▋       | 40/150 [00:00<00:01, 97.95it/s]

Loading blocks.3.norm1.weight:
Loading blocks.3.norm1.bias:
Loading blocks.3.attn.qkv.weight:
Loading blocks.3.attn.qkv.bias:
Loading blocks.3.attn.proj.weight:
Killed

**Comment by HydrogenSulfate** [comment]
感谢关注PaddleVideo的模型套件，看到你的Paddle版本是2.0，报错的函数在2.0和2.1中的确存在差别，
2.0中sublayers是`def sublayers(self, include_sublayers=True):`
2.0的对应链接：https://github.com/PaddlePaddle/Paddle/blob/release%2F2.0/python/paddle/fluid/dygraph/layers.py#L587，
2.1的sublayers是`def sublayers(self, include_self=False):`
2.1的链接：https://github.com/PaddlePaddle/Paddle/blob/release%2F2.1/python/paddle/fluid/dygraph/layers.py#L588
可以试试把include_self=True改为include_sublayers=True，或者升级到[paddle2.1](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html)

另外当多卡训练出现killed但没输出具体报错信息时，建议可以暂时以单卡运行，这样会打印出报错信息，然后修改好没问题了再改回多卡运行。

**Comment by KK-Jiang** [comment]
the config file of timesformer have some mistakes, such as the order of transform, the tensor_shape of Normalization。。。。。。。。。。。。。。。。

**Comment by KK-Jiang** [comment]
the config file of timesformer have some mistakes, such as the order of transform, the tensor_shape of Normalization。。。。。。。。。。。。。。。。

**Comment by HydrogenSulfate** [comment]
> the config file of timesformer have some mistakes, such as the order of transform, the tensor_shape of Normalization。。。。。。。。。。。。。。。。

复现的这个TimeSformer应该是没有问题的，这个模型的数据增强其他模型略有不同，是先做Normalization，在里面转换成tensor，然后在tensor下做数据增强，另外该模型不同于2D的模型先提特征再聚合，该网络中会对时间轴的信息进行注意力学习，所以通道和时间维度的前后关系与其它2D模型也不同，tensor_shape: [1, 1, 1, 3]是没问题的。
如果数据增强报错，可以检查下config文件中的解码backend是否是pyav，用其它backend的话是不会转换成tensor的

**Comment by KK-Jiang** [comment]
> > the config file of timesformer have some mistakes, such as the order of transform, the tensor_shape of Normalization。。。。。。。。。。。。。。。。
> 
> 复现的这个TimeSformer应该是没有问题的，这个模型的数据增强其他模型略有不同，是先做Normalization，在里面转换成tensor，然后在tensor下做数据增强，另外该模型不同于2D的模型先提特征再聚合，该网络中会对时间轴的信息进行注意力学习，所以通道和时间维度的前后关系与其它2D模型也不同，tensor_shape: [1, 1, 1, 3]是没问题的。
> 如果数据增强报错，可以检查下config文件中的解码backend是否是pyav，用其它backend的话是不会转换成tensor的

谢谢您的回答。我这边由于资源的问题，没有验证是否可用。不过相信官方

**Comment by KK-Jiang** [comment]
> > the config file of timesformer have some mistakes, such as the order of transform, the tensor_shape of Normalization。。。。。。。。。。。。。。。。
> 
> 复现的这个TimeSformer应该是没有问题的，这个模型的数据增强其他模型略有不同，是先做Normalization，在里面转换成tensor，然后在tensor下做数据增强，另外该模型不同于2D的模型先提特征再聚合，该网络中会对时间轴的信息进行注意力学习，所以通道和时间维度的前后关系与其它2D模型也不同，tensor_shape: [1, 1, 1, 3]是没问题的。
> 如果数据增强报错，可以检查下config文件中的解码backend是否是pyav，用其它backend的话是不会转换成tensor的

谢谢您的回答。我这边由于资源的问题，没有验证是否可用。不过相信官方
