### ISSUE TITLE
运行extract_feat.py脚本报错

### ISSUE THREAD

**Issue by thorory** [PaddlePaddle/PaddleVideo#189]
![image](https://user-images.githubusercontent.com/10388538/131111459-75a3381b-5952-4aaa-8319-c9f62d7333aa.png)
似乎output_names的维度只有1

**Comment by thorory** [comment]
同时，我看文档上所写的图像的特征大小应当为2048，我这里改为output_name[0]后抽取出来的似乎是（视频帧数/8, 3）

**Comment by littlerookie** [comment]
> 同时，我看文档上所写的图像的特征大小应当为2048，我这里改为output_name[0]后抽取出来的似乎是（视频帧数/8, 3）

请问您这个问题解决了吗，我自己训练的模型，执行这个文件时，输出的大小也是（视频帧数/8,8）

**Comment by xueqin84** [comment]
你怎么解决的呢？我也遇到这个问题
