### ISSUE TITLE
demo 都跑不起来，你们是专门刷 KPI 的么？

### ISSUE THREAD

**Issue by RenderCoder** [PaddlePaddle/PaddleVideo#197]
macOS Python 3.7，就按照 start 文档来一步一步做，能跑通就见鬼了。

**Comment by lujingqiao** [comment]
无法跑通demo，存在各种问题，严重怀疑没有亲自跑过一遍

**Comment by ZhangHandi** [comment]
您好，我们已经对start文档进行了更新，现在已经可以正确运行啦。抱歉之前没有及时更新给您带来不便，感谢您对我们的谅解 :) start文档请查看链接🔗：https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/start.md

**Comment by yuandongbo123** [comment]
官网例子都跑不起来，不知道是我菜，还是你们不用心
