### ISSUE TITLE
FootballAction基于pd2.0训练ppTSM时，不支持SamplerPkl格式

### ISSUE THREAD

**Issue by EnzoLiang** [PaddlePaddle/PaddleVideo#199]
FootballAction基于pd2.0训练ppTSM时，给的pptsm_football_v2.0.yaml文件中的数据格式是SamplerPkl，但是ppTSM提供的yaml文件写的是Sampler，怎么将SamplerPkl转换为Sampler

**Comment by wgh1989** [comment]
输入格式需要自己改下
试试这个版本
https://bj.bcebos.com/v1/acg-algo/models/action-football/PaddleVideo-release-2.1-football.tar
