### ISSUE TITLE
视频流要实现实时的分类，有什么好的思路吗

### ISSUE THREAD

**Issue by nine-city** [PaddlePaddle/PaddleVideo#200]
视频流要实现实时的分类，有什么好的思路吗

**Comment by HydrogenSulfate** [comment]
可以建立一个储存视频帧的buffer池子，比如当前视频有100帧，模型用10帧去分类，那么这个buffer存到第10帧时把buffer里的1\~10帧拿去分类输出标注到视频上，然后当第11帧也存到了buffer里时，拿2\~11帧也拿去分类，结果标注到视频上，类似于一个实时的时间滑动窗口，具体可以调整分类的计算间隔和滑动窗口的时间长度。
