### ISSUE TITLE
AGCN  FSD training problem 

### ISSUE THREAD

**Issue by flydragon2018** [PaddlePaddle/PaddleVideo#210]
**Describe the bug**

training  loss --> NAN  using the baidu dataset 
**To Reproduce**

repo the training process using baidu FSD dataset

**Comment by huangjun12** [comment]
we have updated the config of AGCN on FSD dataset [agcn_fsd.yaml](https://github.com/PaddlePaddle/PaddleVideo/blob/develop/configs/recognition/agcn/agcn_fsd.yaml), please try again~
