### ISSUE TITLE
videotag中tsn读去图片问题

### ISSUE THREAD

**Issue by SpringLclin** [PaddlePaddle/PaddleVideo#213]
![image](https://user-images.githubusercontent.com/86232826/135091109-287603a1-01c4-4fd5-bb94-c2e1e13e0429.png)
这三个方法分别代表着什么含义呢

**Comment by HydrogenSulfate** [comment]
你好，你截图上方的docstring里不是正好写了这三个方法的解释了吗？:sweat_smile:，加@property装饰器是为了更方便和明确地访问属性，否则_data[0/1/2]可能会让人不明所以。
![image](https://user-images.githubusercontent.com/23737287/135955260-238d7138-13a8-4b1a-9fc1-db03f8f8156f.png)
