### ISSUE TITLE
decode函数找不到，翻遍了项目，都没见一个decode函数

### ISSUE THREAD

**Issue by ritalsq** [PaddlePaddle/PaddleVideo#214]
Traceback (most recent call last):
  File "quick_start.py", line 4, in <module>
    result=clas.predict(video_file)
  File "/opt/conda/lib/python3.7/site-packages/ppvideo/tools/paddlevideo_clas.py", line 294, in predict
    v = utils.decode(video, self.args)
AttributeError: module 'tools.utils' has no attribute 'decode'

**Comment by HydrogenSulfate** [comment]
你好，可以用这个[tools/utils.py](https://github.com/PaddlePaddle/PaddleVideo/blob/e71990835c5fad34b068530171436d84ee81f23b/tools/utils.py)的代码覆盖掉你的tools/utils.py，里面有decode、preprocess、postprocess这三个缺失的函数，可以试试看还有没有问题

**Comment by ritalsq** [comment]
好的，我看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月26日(周二) 下午4:31
收件人: ***@***.***&gt;;
抄送: "attack and ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleVideo] decode函数找不到，翻遍了项目，都没见一个decode函数 (#214)




 
你好，可以将这个PR里tools/utils.py的代码覆盖掉你的tools/utils.py，里面有decode、preprocess、postprocess这三个缺失的函数，可以试试看还有没有问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
