### ISSUE TITLE
希望训练过程打印eta

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleVideo#215]
顺便问一下，训练过程中一边训练一边eval，每N个epoch save一下，这些功能现在有吗？有的话配置文件示例哪里有？

**Comment by HydrogenSulfate** [comment]
1. ETA功能目前还未加入
2. 一边训练一边eval功能有，以pptsm为例，run.sh中训练pptsm的命令是
```bash
python3.7 -B -m paddle.distributed.launch --gpus="0,1,2,3,4,5,6,7"  --log_dir=log_pptsm  main.py  --validate -c configs/recognition/pptsm/pptsm_k400_frames_uniform.yaml
```
  其中`--validate`就指定了训练过程中会进行validate（eval），然后每次会覆盖保存下eval分数最高的ckpt作为best_ckpt，默认eval间隔是1，你也可以像3. 一样在配置文件中指定val_interval的间隔数。

3. 每隔N个epoch save一下功能目前也有，这个N需要在config中配置一下，同样以TimeSformer的配置文件为例，https://github.com/PaddlePaddle/PaddleVideo/blob/develop/configs/recognition/timesformer/timesformer_k400_videos.yaml#L140
140行`save_interval: 3`指定了每隔3个epoch保存下ckpt，这个3就是你说的N，你想开启这个功能就在对应模型的配置文件中加入这一行选项即可（有的模型可能没这行代码，就没开启这个功能）。
