### ISSUE TITLE
NTU-RGB+D数据集下载解压后，为什么只有一个文件，上传到AI Studio仍然看不到目录

### ISSUE THREAD

**Issue by scholar-fuck** [PaddlePaddle/PaddleVideo#225]
我想在AI Studio平台 用AGCN去训练NTU-RGB+D数据集，后续会打算进一步处理该数据集，精简一些动作。可是下载的NTU-RGB+D数据集只有一个文件，看不到目录，请问，正确的使用AGCN 训练NTU-RGB+D的使用方式是什么呢？

**Comment by huangjun12** [comment]
数据使用方式参考： https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/dataset/ntu-rgbd.md

下载解压后的目录如下：
```txt
─── NTU-RGB-D
    ├── xsub
    │   ├── train_data.npy
    │   ├── train_label.pkl
    │   ├── val_data.npy
    │   └── val_label.pkl
    └── xview
        ├── train_data.npy
        ├── train_label.pkl
        ├── val_data.npy
        └── val_label.pkl
```

在对应的配置文件[agcn_ntucs.yaml](https://github.com/PaddlePaddle/PaddleVideo/blob/12508beae610e2af5301a82f62c00678931d45d0/configs/recognition/agcn/agcn_ntucs.yaml#L18)里通过`file_path`和`label_path`字段指定数据路径即可使用
