### ISSUE TITLE
文档链接错误

### ISSUE THREAD

**Issue by ToscanaGoGithub** [PaddlePaddle/PaddleVideo#231]
https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/recognition/agcn.md处文档
模型优化细节参考AGCN模型详解，此处关联连接错误，并不是真实的AGCN模型详解文档链接。
还请更换

**Comment by huangjun12** [comment]
目前还没有文档，可以参考[视频](https://www.bilibili.com/video/BV1w3411172G)模型优化部分讲解
