### ISSUE TITLE
训练过程中valid的top1_avg的数值与实际不符合

### ISSUE THREAD

**Issue by desires19** [PaddlePaddle/PaddleVideo#235]
训练过程中valid的top1_avg的数值与实际不符合

**Comment by HydrogenSulfate** [comment]
能详细说说具体怎么回事吗，有的模型valid和test数据预处理的策略是不一样的，分数可能会有差异

**Comment by desires19** [comment]
在paddlevedio\taskes\train.py文件的239行左右的
record_list[name].update(value, batch_size)
修改为record_list[name].update(value, valid_batch_size),
可以解决这个bug

**Comment by desires19** [comment]
同时需要在yaml中设置valid_btach_size。为尽量精准，需要valid_batch_size可以被验证集的数据样本数整除

**Comment by HydrogenSulfate** [comment]
> 在paddlevedio\taskes\train.py文件的239行左右的 record_list[name].update(value, batch_size) 修改为record_list[name].update(value, valid_batch_size), 可以解决这个bug

感谢建议，后续会修复这个BUG

**Comment by huangjun12** [comment]
pls refer to #237
