### ISSUE TITLE
方便分享一下NTU-RGB-D/(FSD-10)视频数据集的处理脚本吗？

### ISSUE THREAD

**Issue by scholar-fuck** [PaddlePaddle/PaddleVideo#240]
准备用自己的视频数据集做一些动作识别，思路也是先用openpose识别多帧的关键点，然后把多帧的关键点处理成【N,C,T,V，M】的格式输入到ST-GCN中。
能否方便分享一下 将识别出的多帧人体关键点结果处理成ST-GCN需要的输入形式 的处理脚本呢？

**Comment by ZhaoJingjing713** [comment]
> https://github.com/HaxiSnake/skeleton_scripts
这是作者制作数据集所用，如果还需要具体步骤可以联系我
