### ISSUE TITLE
不能用GPU进行推理

### ISSUE THREAD

**Issue by cendelian** [PaddlePaddle/PaddleVideo#249]
环境 
cuda11.0 / cuda 11.2
cudnn8.2
paddle2.2

运行predict.py会报错，不能使用GPU做推理或者测试速度

python3.7 predict.py --enable_benchmark=True --model_file inference/TSM/TSM.pdmodel  --params_file inference/TSM/TSM.pdiparams

**
W1119 16:52:23.713899 36530 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W1119 16:52:23.716542 36530 device_context.cc:465] device: 0, cuDNN Version: 8.2.
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1637311945 (unix time) try "date -d @1637311945" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 36530 (TID 0x7f04bf577700) from PID 0 ***]

Segmentation fault (core dumped)**

**Comment by sean186** [comment]
I have the same problem, is it solved?

> 环境 cuda11.0 / cuda 11.2 cudnn8.2 paddle2.2
> 
> 运行predict.py会报错，不能使用GPU做推理或者测试速度
> 
> python3.7 predict.py --enable_benchmark=True --model_file inference/TSM/TSM.pdmodel --params_file inference/TSM/TSM.pdiparams
> 
> ## **
> W1119 16:52:23.713899 36530 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
> W1119 16:52:23.716542 36530 device_context.cc:465] device: 0, cuDNN Version: 8.2.
> ## C++ Traceback (most recent call last):
> No stack trace in paddle, may be caused by external reasons.
> 
> ## Error Message Summary:
> FatalError: `Segmentation fault` is detected by the operating system. [TimeInfo: *** Aborted at 1637311945 (unix time) try "date -d @1637311945" if you are using GNU date ***] [SignalInfo: *** SIGSEGV (@0x0) received by PID 36530 (TID 0x7f04bf577700) from PID 0 ***]
> 
> Segmentation fault (core dumped)**

I have the same problem, is it solved?

**Comment by sean186** [comment]
> 

I have the same problem, is it solved?

**Comment by cendelian** [comment]
已经解决， 将cudnn版本降到7.6.5 就可以。。。。。。。。。。。。。。。。。。。。。。。。。
