### ISSUE TITLE
skelenton 序列随机抽帧无法保持有序

### ISSUE THREAD

**Issue by SigureMo** [PaddlePaddle/PaddleVideo#274]
https://github.com/PaddlePaddle/PaddleVideo/blob/e5f3bcb05b2f7232a3ba227c6802ccfe0d4c1f41/paddlevideo/loader/pipelines/skeleton_pipeline.py#L56-L62

骨骼序列数据在上述随机抽帧逻辑中（np.random.choice）貌似无法保持顺序抽取，序列会直接乱掉，请问这是否是预期的效果呢？

可以在之后加一行 `index = np.sort(index)` 以保证有序性

```
>>> x = np.random.choice(100, 10, replace=False)
>>> print(x)
[55 89 99 25 16 45 71 51 10 61]
>>> y = np.sort(x)
>>> print(y)
[10 16 25 45 51 55 61 71 89 99]
```

**Comment by luyao-cv** [comment]
可以的，不影响
