### ISSUE TITLE
官方能给个长视频预测分类的predict吗

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/PaddleVideo#306]
我使用pp-tsm训练出来一个模型，也可以用predict.py预测但是有个问题，你这个只能输入一个短视频预测结果，但是在实际情况下，是需要外接摄像头实时预测的。在mmaction2官方就给了一个长视频预测，可以很容易改为实时预测，但是paddlevideo却没有这样例子。mmaction2是默认对长视频抽取连续25帧作预测，当然也可以改成自己帧数。我在mmaction2成功实现实时检测要求，但是官方却没有长视频预测案例，我不会改，希望官方加个长视频预测案例。

**Comment by aureosun** [comment]
求问你最后这个解决了么
