### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by peteli25** [PaddlePaddle/PaddleVideo#330]
Traceback (most recent call last):
  File "extract_bmn_for_tabletennis.py", line 19, in <module>
    import models.bmn_infer as prop_model
ModuleNotFoundError: No module named 'models'

**Comment by Fred1991** [comment]
修改sys.path.append路径

**Comment by Fred1991** [comment]
/PaddleVideo/applications/TableTennis/predict/action_detect/
