### ISSUE TITLE
applications/VideoTag/videotag_test.py 如何测试自定义数据

### ISSUE THREAD

**Issue by yfq512** [PaddlePaddle/PaddleVideo#341]
applications/VideoTag/videotag_test.py 如何测试自定义数据

**Comment by yfq512** [comment]
我想修改为输入是：一个视频路径，输出是：该视频的预测结果，有相关的例子么？

**Comment by huangjun12** [comment]
可以参考这个文档哈 https://github.com/PaddlePaddle/PaddleVideo/blob/develop/applications/VideoTag/Test.md
