### ISSUE TITLE
EIVideo视频标注工具没有默认权重

### ISSUE THREAD

**Issue by ZhijunLStudio** [PaddlePaddle/PaddleVideo#358]
运行python QEIVideo/start.py时，没有默认权重，程序直接报错，请问能给一下默认权重的下载吗？

OSError: E:\PaddleVideo-develop\applications\EIVideo\EIVideo\model/default_manet.pdparams not exist

**Comment by GT-ZhangAcer** [comment]
感谢关注，目前EIVideo的前后端仍有一些不够完善之处，如方便可移步至下方仓库，使用最新版本代码：
https://github.com/QPT-Family/EIVideo  

也可根据该链接，获取默认的权重文件：
https://videotag.bj.bcebos.com/PaddleVideo-release2.2/MANet_EIVideo.pdparams
