### ISSUE TITLE
求问yaml文件中resume和控制命令-w的区别

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/PaddleVideo#369]
即使再yaml文件中指定了错误的内容，程序依旧照例执行，想问一下是否resume是没有意义的指定条目？以及-w是否指定-pdparams即可接续训练？

**Comment by huangjun12** [comment]
`resume`用于继续训练，即训练过程中断后，继续开启训练。既需要load模型参数文件，也需要load优化器参数文件。

`-w`用于模型微调，即模型在数据集A上训练好之后，在训练集B上微调，重新训练。只需要load模型文件。

**Comment by Liyulingyue** [comment]
问题解决~

**Comment by JingXuGitHub** [comment]
> `resume`用于继续训练，即训练过程中断后，继续开启训练。既需要load模型参数文件，也需要load优化器参数文件。
> 
> `-w`用于模型微调，即模型在数据集A上训练好之后，在训练集B上微调，重新训练。只需要load模型文件。

如果微调的话，是否只需要使用-w参数，load预训练模型参数？这个模型参数跟配置文件中pretrained参数，是同一个参数吗？这两个参数有什么区别？

**Comment by Liyulingyue** [comment]
> > `resume`用于继续训练，即训练过程中断后，继续开启训练。既需要load模型参数文件，也需要load优化器参数文件。
> > `-w`用于模型微调，即模型在数据集A上训练好之后，在训练集B上微调，重新训练。只需要load模型文件。
> 
> 如果微调的话，是否只需要使用-w参数，load预训练模型参数？这个模型参数跟配置文件中pretrained参数，是同一个参数吗？这两个参数有什么区别？

应该没啥区别

**Comment by JingXuGitHub** [comment]
> > > `resume`用于继续训练，即训练过程中断后，继续开启训练。既需要load模型参数文件，也需要load优化器参数文件。
> > > `-w`用于模型微调，即模型在数据集A上训练好之后，在训练集B上微调，重新训练。只需要load模型文件。
> > 
> > 
> > 如果微调的话，是否只需要使用-w参数，load预训练模型参数？这个模型参数跟配置文件中pretrained参数，是同一个参数吗？这两个参数有什么区别？
> 
> 应该没啥区别

谢谢，那就是说微调训练的话，就只需要在配置文件中设置pretrained参数，而不需要在外部再使用-w参数。那如果是从头训练的话，这两个参数是不是都不需要设置？是不是这样的？从头训练的话，输出的参数是保存在-output里面的是吧？
