### ISSUE TITLE
SlowFast+Fast R-CNN.  执行静态图模型推理时在predictor.run()步骤报错:ExternalError: CUDA error(700), an illegal memory access was encountered.

### ISSUE THREAD

**Issue by PyAllegro** [PaddlePaddle/PaddleVideo#440]
基于[百度飞桨PaddlePaddle官方教程《基于时空信息的异常行为检测》，创建了自定义行为识别数据集（共3类行为）。然后完成了模型训练与静态图转换，但基于训练好的模型在进行静态图推理时，报出以下错误：
![屏幕截图 2022-05-25 16:59:10](https://user-images.githubusercontent.com/38966664/170229047-9d29fa38-bfb7-45df-ba0f-cd86814d8698.png)
![屏幕截图 2022-05-25 17:03:17](https://user-images.githubusercontent.com/38966664/170229100-4bd6c151-c0f9-4553-8537-707328010cc3.png)
模型训练期间的输出如下：
![屏幕截图 2022-05-25 17:24:21](https://user-images.githubusercontent.com/38966664/170229603-3003564c-5137-4b3a-9c95-61cc99d76e36.png)
在查询类似issues时发现有人说是图像输入与模型输入不匹配问题，但应该不是该问题，如能给予帮助或建议，非常感谢！

**Comment by XYZ-916** [comment]
你好，请问能否把你训练好的模型，配置文件以及其他修改的代码提供下吗？目前的这些信息不太能定位出问题的位置，谢谢。

**Comment by PyAllegro** [comment]
> 
感谢回复，因为github有文件上传大小限制，因此还希望能够提供邮箱我这边私发你模型权重文件谢谢！上传的文件列表如下（主要修改的地方为数据集的类别标签、模型训练与评估相关的配置文件信息）。
[abnoraml_action_yaml.zip](https://github.com/PaddlePaddle/PaddleVideo/files/8866273/abnoraml_action_yaml.zip)
[AVA_SlowFast_FastRcnn_pdmodel.zip](https://github.com/PaddlePaddle/PaddleVideo/files/8866275/AVA_SlowFast_FastRcnn_pdmodel.zip)
[abnormal_action_list_pbtxt.zip](https://github.com/PaddlePaddle/PaddleVideo/files/8866278/abnormal_action_list_pbtxt.zip)
