### ISSUE TITLE
各位大佬好，请教个问题，利用ST-GCN进行多种类行为识别推理时，如何修改原始代码？目前推理时，程序报错，如下图所示：

### ISSUE THREAD

**Issue by tuodi** [PaddlePaddle/PaddleVideo#453]
![1](https://user-images.githubusercontent.com/33543014/173319950-66d8e228-5e03-4b40-b0bd-14321023c43e.jpg)

**Comment by huangjun12** [comment]
看报错是输入的shape不对

**Comment by tuodi** [comment]
有配置文件或者在代码的什么位置可以修改吗？谢谢。



1021768023
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleVideo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月14日(星期二) 晚上7:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleVideo] 各位大佬好，请教个问题，利用ST-GCN进行多种类行为识别推理时，如何修改原始代码？目前推理时，程序报错，如下图所示： (Issue #453)





 
看报错是输入的shape不对

**Comment by huangjun12** [comment]
可以检查一下，
[导出模型时指定的shape](https://github.com/PaddlePaddle/PaddleVideo/blob/985624a928ab904f795ef31c5598d24d9becc093/tools/export_model.py#L155)和[模型推理时输入数据的shape](https://github.com/PaddlePaddle/PaddleVideo/blob/985624a928ab904f795ef31c5598d24d9becc093/tools/utils.py#L776)是否一致
