### ISSUE TITLE
BMN模型测试的bug

### ISSUE THREAD

**Issue by wang136618693** [PaddlePaddle/PaddleVideo#474]
您好！当我用预训练模型BMN.pdparams运行python main.py --test -c configs/localization/bmn.yaml -w output/BMN/BMN_epoch_00009.pdparams -o DATASET.test_batch_size=1进行模型测试的时候（数据集用的也是您这里提供的处理好的数据集）出现了bug，bug如下：

G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:24: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE i
nstead.
  'nearest': Image.NEAREST,
G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:25: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:26: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.        
  'bicubic': Image.BICUBIC,
G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:27: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:28: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.        
  'lanczos': Image.LANCZOS,
G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:29: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.        
  'hamming': Image.HAMMING
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    main()
  File "main.py", line 119, in main
    test_model(cfg, weights=args.weights, parallel=parallel)
  File "E:\anaconda\envs\bmn\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\anaconda\envs\bmn\lib\site-packages\paddle\fluid\dygraph\base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\tasks\test.py", line 87, in test_model
    Metric.accumulate()
  File "G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\metrics\bmn_metric.py", line 202, in accumulate
    self.result_path)
  File "G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\metrics\bmn_metric.py", line 234, in bmn_post_processing
    p.start()
  File "E:\anaconda\envs\bmn\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "E:\anaconda\envs\bmn\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\anaconda\envs\bmn\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\anaconda\envs\bmn\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\anaconda\envs\bmn\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'paddlevideo.metrics.bmn_metric.BMNMetric'>: it's not the same object as paddlevideo.metrics.bmn_metric.BMNMetric
G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:24: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE i
nstead.
  'nearest': Image.NEAREST,
G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:25: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:26: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.        
  'bicubic': Image.BICUBIC,
G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:27: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:28: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.        
  'lanczos': Image.LANCZOS,
G:\wangdinghong\PaddleVideo\PaddleVideo-develop\paddlevideo\loader\pipelines\augmentations_ava.py:29: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.        
  'hamming': Image.HAMMING

(bmn) G:\wangdinghong\PaddleVideo\PaddleVideo-develop>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\anaconda\envs\bmn\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\anaconda\envs\bmn\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

大佬望您尽快解答，谢谢！

**Comment by huangjun12** [comment]
请问下现在解决了嘛
看报错是文件写入的时候又做了读取操作
```txt
EOFError: Ran out of input
```
等模型和数据都下载好之后，再跑应该就ok了

**Comment by wang136618693** [comment]
我这个是在window10跑的，会报这个错，但是在ubuntu20.04上跑不会报错。所以我用Ubuntu了，不用window10了。
