### ISSUE TITLE
环境配置报错

### ISSUE THREAD

**Issue by hellmo718** [PaddlePaddle/PaddleVideo#479]
安装paddlevideo的环境时候要求安装nccl，但是我的服务器是单GPU的，不需要安装nccl应该也能搭建paddlevideo的环境吧。但是最后使用ppvideo --model_name='ppTSM' --video_file='data/example.avi'语句启用环境时候报错，说没有“ava_predict”模块，有人能帮我解答一下吗？谢谢
<img width="842" alt="5b7a8703a80489d23dc39f21f32ea35" src="https://user-images.githubusercontent.com/71963185/179011724-38bbed53-3b8a-4b88-b8be-86b6fb86f48b.png">

**Comment by onedayCVPR** [comment]
先将 padlennlp 这些包全装上吧

**Comment by hellmo718** [comment]
我看安装说明里面没有说要装paddlenlp吧，而且我只是在安装环境后使用测试环境的时候报这个错误，还没开始调用模型进行训练呢，应该用不到额外的库吧。

**Comment by huangjun12** [comment]
可以参考这个[pr](https://github.com/PaddlePaddle/PaddleVideo/pull/485)
wheel包最近会有更新

**Comment by linwoodf33** [comment]
tools/utils.py 报错的地方加个.指定为当前目录
