### ISSUE TITLE
请问打架视频行为识别的config文件在哪？pptsm_fight_frames_dense.yaml

### ISSUE THREAD

**Issue by chen1234520** [PaddlePaddle/PaddleVideo#484]
请问打架视频行为识别的config文件在哪？
pptsm_fight_frames_dense.yaml

**Comment by huangjun12** [comment]
https://github.com/PaddlePaddle/PaddleVideo/tree/develop/applications/FightRecognition 这里哈

**Comment by chen1234520** [comment]
> https://github.com/PaddlePaddle/PaddleVideo/tree/develop/applications/FightRecognition 这里哈

感谢！
