### ISSUE TITLE
请问 pptsm_mv2_k400_videos_uniform_fight.yaml 里面classnum在哪里设置？ 

### ISSUE THREAD

**Issue by chen1234520** [PaddlePaddle/PaddleVideo#486]
看pptsm的config文件中，resnet主干网络的head中有classnum，但是mv2主干的head中没有classnum，请问mv2的类别数量怎么设置？是因为使用的head不一样吗，mv2的主干可以搭配ppTSMHead使用吗？

感谢！

>>pptsm_k400_frames_dense_r101.yaml
MODEL: #MODEL field
    framework: "Recognizer2D"
    backbone: 
        name: "ResNetTweaksTSM"
    head:
        name: "ppTSMHead"
        num_classes: 400

>>pptsm_mv2_k400_videos_uniform.yaml
MODEL: #MODEL field
    framework: "Recognizer2D" 
    backbone:
        name: "PPTSM_MobileNetV2".
    head:
        name: "MoViNetHead"

**Comment by huangjun12** [comment]
在backbone里设置class_num就行了  https://github.com/PaddlePaddle/PaddleVideo/blob/16e2b03066c2299a2a97d9ebe303af2113007c76/paddlevideo/modeling/backbones/pptsm_mv2.py#L165 会通过这一行生效

**Comment by chen1234520** [comment]
> 在backbone里设置class_num就行了
> 
> https://github.com/PaddlePaddle/PaddleVideo/blob/16e2b03066c2299a2a97d9ebe303af2113007c76/paddlevideo/modeling/backbones/pptsm_mv2.py#L165
> 
> 会通过这一行生效

非常感谢，paddle做的很棒！
