### ISSUE TITLE
各位好，我想问一下，paddlevideo项目train.py文件中的权重初始化代码在哪里？谢谢！

### ISSUE THREAD

**Issue by tuodi** [PaddlePaddle/PaddleVideo#493]
具体路径为：PaddleVideo-develip/paddlevideo/tasks/train.py

**Comment by huangjun12** [comment]
权重初始化实现在backbone/head下的各模型文件中，如 https://github.com/PaddlePaddle/PaddleVideo/blob/e286eea454660717e1b6233a4d6c962f9ba4a180/paddlevideo/modeling/backbones/pptsm_v2.py#L310 在framewor中的init方法里调用 https://github.com/PaddlePaddle/PaddleVideo/blob/e286eea454660717e1b6233a4d6c962f9ba4a180/paddlevideo/modeling/framework/recognizers/base.py#L27
