### ISSUE TITLE
ST-GCN模型泛化能力不好，正样本为实际场景数据，负样本为官网KTH数据集，是否将负样本更改为和正样本一样场景的数据更好呢？

### ISSUE THREAD

**Issue by tuodi** [PaddlePaddle/PaddleVideo#494]
在PPHuman项目中，咱们采集的正负样本是摔倒视频，我看负样本说的是：其他场景中的摔倒及非摔倒的动作场景，这个是咱们自己采集的还是网上的？对结果是否存在影响？谢谢！

**Comment by zoooo0820** [comment]
正负样本的区分是在同一个场景中，按动作不同进行的区分。实际数据存在多个场景，这些场景中均按上述方法区分了正负样本没具体数据说明可以参考文档中的介绍。

在实际使用中，尽量保证场景和训练数据一致以保证效果
