### ISSUE TITLE
pptimetransformer：预训练权重

### ISSUE THREAD

**Issue by syyxtl** [PaddlePaddle/PaddleVideo#496]
<img width="907" alt="截屏2022-08-03 下午7 51 00" src="https://user-images.githubusercontent.com/66545456/182601130-82c5349b-f447-4297-b5f0-8fc4ff9634ad.png">
我想确认一下这个预训练模型明名的问题，没有上传错吧。
<img width="907" alt="截屏2022-08-03 下午7 51 01"  src="https://user-images.githubusercontent.com/66545456/182601706-2159d57f-0548-48a1-a90e-035aa4c7e935.png">

因为我看到有些层没有加载进去

**Comment by HydrogenSulfate** [comment]
没有问题的，因为预训练模型是2D的ViT，这些层就是没有的
