### ISSUE TITLE
out of memory at GPU 0

### ISSUE THREAD

**Issue by 284nnuS** [PaddlePaddle/PaddleVideo#502]
I'm trying to training model but i have a issue like:
Out of memory error on GPU 0. Cannot allocate 80.000000MB memory on GPU 0, 10.647278GB memory has been allocated and available memory is only 108.750000MB.
Btw i see my available memory is greater than GPU 0. So How can i fix this issue? I don't want to reduce the num worker to 0 because it very slow for training the model

**Comment by huangjun12** [comment]
decrease the batch_size, and adjusted learning rate linearly.
