### ISSUE TITLE
pptsm全量模型在哪里下载？本git仓只有一部分，全量的没找到，请给个连接

### ISSUE THREAD

**Issue by aureosun** [PaddlePaddle/PaddleVideo#517]
全量模型包括mobilenet pclnet resnet在ucf101或者k-400上的模型，请求给个连接，现在全不分散在各处，不太好找

**Comment by huangjun12** [comment]
现在训练好的模型下载链接在这里

https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/model_zoo/recognition/pp-tsm.md#7-模型库下载
