### ISSUE TITLE
Application:MultimodalVideoTag 数据下载不了

### ISSUE THREAD

**Issue by zhanglaplace** [PaddlePaddle/PaddleVideo#568]
![image](https://user-images.githubusercontent.com/12178974/212796764-60bade28-07dc-4bb3-9a7f-1e189b26dad0.png)
![image](https://user-images.githubusercontent.com/12178974/212796837-adac51e9-4da4-4f22-9e2b-982f3d96b652.png)

**Comment by huangjun12** [comment]
已修复 #575
