### ISSUE TITLE
是不是都没人维护了，关于应用的issue提交了很多次都没管。。。。真是服了

### ISSUE THREAD

**Issue by zhanglaplace** [PaddlePaddle/PaddleVideo#570]
issue内很多反应readme内部的数据或者模型失效无法下载的问题，都没人解决。
也不知道这个有什么难度，就是没人管。服气

**Comment by huangjun12** [comment]
抱歉，之前因为数据隐私问题，有些bucket被设置为私有了，这边正与业务方协商沟通中

**Comment by zhanglaplace** [comment]
> 抱歉，之前因为数据隐私问题，有些bucket被设置为私有了，这边正与业务方协商沟通中

好的，多谢，辛苦有更新了回复下

**Comment by huangjun12** [comment]
已修复，参考 #575
