### ISSUE TITLE
Input video for table tennis application

### ISSUE THREAD

**Issue by TrinityNeo99** [PaddlePaddle/PaddleVideo#571]
Dear author, the demo input video is xxx.pkl, can I use a regular video file like xxx.mp4 or xxx.avi?
I wonder If there are some tools to convert regular video to "pkl" format as your definition, thank you very much

**Comment by huangjun12** [comment]
.pkl file is composed of frames, so you can decode video to frames, then save frames to .pkl file

**Comment by TrinityNeo99** [comment]
Thanks you very much
