### ISSUE TITLE
How to modify feature dimention using TSN extractor?

### ISSUE THREAD

**Issue by TrinityNeo99** [PaddlePaddle/PaddleVideo#572]
Dear author, I want to leverage BMN model which requires the TSN feature (400) as default for my own dataset, but the feature extracted by tsn_extractor in your project is 2048 by default.  I wonder if I can use your pre-trained model to finish my job, thanks a lot.

"tsn提取的特征向量维度为帧数*特征维度，默认为300 * 2048" in [tsn_extractor: README](https://github.com/PaddlePaddle/PaddleVideo/blob/develop/applications/VideoTag/FineTune.md)

**Comment by huangjun12** [comment]
you can change BMN model input dimension from 400 to 2048 for fine-tune

**Comment by TrinityNeo99** [comment]
So if I adjust input dimension, do I need to re-train the BMN model?

**Comment by huangjun12** [comment]
Yeah, you need to re-train the BMN model.
Another way is that, you can resize 2048 to 400. But it may not work well.
