### ISSUE TITLE
基于linux安装报ERROR: Could not find a version that satisfies the requirement decord==0.4.2 (from ppvideo==2.3.0) (from versions: none) ERROR: No matching distribution found for decord==0.4.2 (from ppvideo==2.3.0)

### ISSUE THREAD

**Issue by xiangzidetiandi** [PaddlePaddle/PaddleVideo#579]
ERROR: Could not find a version that satisfies the requirement decord==0.4.2 (from ppvideo==2.3.0) (from versions: none)
ERROR: No matching distribution found for decord==0.4.2 (from ppvideo==2.3.0)
![image](https://user-images.githubusercontent.com/4446184/219857713-5c404836-3f90-4b24-9c72-1119b841d0c7.png)

**Comment by xiangzidetiandi** [comment]
ERROR: Could not find a version that satisfies the requirement decord==0.4.2 (from ppvideo==2.3.0) (from versions: none)
ERROR: No matching distribution found for decord==0.4.2 (from ppvideo==2.3.0)
![image](https://user-images.githubusercontent.com/4446184/219857689-ff9c3faa-0a11-4237-8312-d4881a84bae9.png)

**Comment by yangguoping123** [comment]
python版本不对

**Comment by liuboye** [comment]
楼上用的哪个版本，mac我也遇到同样问题

**Comment by liuboye** [comment]
> python版本不对

mac下3.7.4也是报错
