### ISSUE TITLE
当我运行 !python3.8 main.py --test -c configs/multimodal/actbert/actbert_msrvtt.yaml -w ActBERT.pdparams 出现如下的中间结果，这是出错了吗？

### ISSUE THREAD

**Issue by aspnetcs** [PaddlePaddle/PaddleVideo#580]
b'\x80\x04\x95\x0e\xf4\x00\x00\x00\x00\x00\x00}\x94(\x8c\x08video_id\x94\x8c\tvideo9770\x94\x8c\x07image_h\x94K\xf0\x8c\x07image_w\x94M@\x01\x8c\tnum_boxes\x94K\x02\x8c\x05boxes\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x02K\x04\x86\x94h\n\x8c\x05dtype\x94\x93\x94\x8c\x02f4\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C S\x13yB\xc04\xf3A\x18\x8e\x94C\x9a\x99oC/p\x0bC3\xb5\xdf?\xe4\x036C\xa2z1B\x94t\x94b\x8c\x08features\x94h\th\x0cK\x00\x85\x94h\x0e\x87\x94R\x94(K\x01K\x02M\x00\x08\x86\x94h\x16\x89B\x00@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0n\xfa>\x00\x00\x00\x00C\x1f\x14@\x04\xc4+?\x84\xb4\xdc<\xdfP^<G&\x82@\xf9\xef\x01@\x10\x83\x9a=\xf4k\xa0>\x0eg\x11?\xae%m>\xf0\x0b\x15>\xc4.{@\x00\x00\x00\x00*\x90\x1e@\x00\x00\x00\x00?\xfc\xb3?\x11^\xe2?\'\x13\xfa<\xd5\x10x?H\x1e%?\x00\x00\x00\x00\x00\x00\x00\x00\xce\x08\xf0>\xac*\xb4<k\xea:@\x00\x00\x00\x00/zT?*\x93^>\xe6\xf3\x12=tj\xb0>\x11\x11d@o\x84\x1d@\xd6\xc4\xd5=\xe6>\xc1;\x9b\xb3\xbd?\xb9\xfe\x0c?\x01\x9fP@\x00\x00\x00\x00\xff\xf5\x99@\x0e\x95\x9c=\xee\x1d\x8c?<\x8c\x00A\x8e\x11t>\xcc6\xbc?\n\xac\x01?\x076\x9f>\x03-b@\x9f\x133<\xaeC*@\xd0\xf0\xdc>z\xb2\xa4@\xb2}E=X\xb4\x87@\xf9\x1c\xf0?#\x95i?b\xdfX@p\xf3\xbd>\x1a\x9d\xb3>\xb8\x12t=\xad\x18\x19=\x9eX\xa6@\xc1\x9a=@?\x02[?\xbb\x15\xa4A#\xb0\x88>\xa8h8@\xb6T\xae?\xc9\xc5\xe1<\xf6\xbbL<;\x10\t@\xdf\xc6\x93@\xc3\x9c\x16?\x8e \xb9?\x00\x00\x00\x00^\x9d\xb4>\x00\x00\x00\x00\xa7\x10\xa3>\xbb\x13C?\xb2\xb0\x91?\x08\xd9\xb1?\x00\x00\x00\x00qJ\xa1;\xd0\xf5\tA\x00\x00\x00\x00\x07\x006@\xea\xf0\xfb<\xe2\xe6\xd4?\x14\xb8\xb4?v\xb3\x8c?+A\xac@\x00\x00\x00\x00\xe5\xf2\x89>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00oh\xec?\xbfX\xba=\xb

**Comment by Jmlie** [comment]
解决了吗？
