### ISSUE TITLE
ppvideo --model_name='ppTSM_v2' --use_gpu=True --video_file='data/example.avi'  不工作

### ISSUE THREAD

**Issue by PhilanthropistBright** [PaddlePaddle/PaddleVideo#627]
按照教程安装完环境以后  使用命令
ppvideo --model_name='ppTSM_v2' --use_gpu=True --video_file='data/example.avi'

返回的是
d:\py37\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

Inference models that Paddle provides are listed as follows:
['ppTSM', 'ppTSM_v2']

Traceback (most recent call last):
  File "d:\py37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\py37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\py37\Scripts\ppvideo.exe\__main__.py", line 7, in <module>
  File "d:\py37\lib\site-packages\ppvideo\tools\wheel.py", line 349, in main
    clas_engine = PaddleVideo(**(args.__dict__))
  File "d:\py37\lib\site-packages\ppvideo\tools\wheel.py", line 257, in __init__
    'If you want to use your own model, Please input model_file as model path!'
Exception: If you want to use your own model, Please input model_file as model path!

没有预期的显示出来那种结果

我用anaconda 创建的python3.7环境
在win11下

**Comment by PhilanthropistBright** [comment]
我自己解决了   不能用单引号  要用双引号

**Comment by PhilanthropistBright** [comment]
我自己解决了 不能用单引号 要用双引号

**Comment by yll1** [comment]
> 我自己解决了 不能用单引号 要用双引号
您好，我想请教一下知道您用的PaddleVideo是哪个版本的呢？还有您是怎么安装ppvideo的，我这边用win10安装的ppvideo ，无法直接用ppvideo --model_name='ppTSM_v2' --use_gpu=True --video_file='data/example.avi' 这个命令，只能用from ppvideo import PaddleVideo这个命令调用PaddleVideo。大佬，帮忙看看，万分感谢哈！@PhilanthropistBright

**Comment by yll1** [comment]
> 我自己解决了 不能用单引号 要用双引号

我自己解决了 不能用单引号 要用双引号
您好，我想请教一下知道您用的PaddleVideo是哪个版本的呢？还有您是怎么安装ppvideo的，我这边用win10安装的ppvideo ，无法直接用ppvideo --model_name='ppTSM_v2' --use_gpu=True --video_file='data/example.avi' 这个命令，只能用from ppvideo import PaddleVideo这个命令调用PaddleVideo。大佬，帮忙看看，万分感谢哈！@PhilanthropistBright
