### ISSUE TITLE
The model and datasets for BasketballAction can not download now.

### ISSUE THREAD

**Issue by JerryPengNJ** [PaddlePaddle/PaddleVideo#630]
##  Following the title, the model and datasets for BasketballAction can not download now. I will appreciate it if you can fix it as soon as possible.
<img width="1074" alt="Screenshot 2023-06-06 at 11 18 01" src="https://github.com/PaddlePaddle/PaddleVideo/assets/104618943/6e83962c-44b0-4170-9b8b-7e25257f2df3">

**Comment by westfish** [comment]
I’m sorry, but this repo is no longer updated.
