### ISSUE TITLE
Video information extraction

### ISSUE THREAD

**Issue by Tortoise17** [PaddlePaddle/PaddleVideo#681]
I have seen this repo as very informative and helpful.
I want to use it for the information extraction from video like objects and actions as human readable format and export it to save information. Is it possible from any pipeline using this library? I have seen application examples but could not figure out completely. If you could give some hints.
Your kind guide is highly appreciated.

**Comment by jerrywgz** [comment]
you could refer to the document https://github.com/PaddlePaddle/PaddleVideo/blob/develop/docs/zh-CN/quick_start.md for action recognition, and more demand could send to PaddleMIX（https://github.com/PaddlePaddle/PaddleMIX/tree/develop） for large multimodal model

**Comment by jerrywgz** [comment]
you could also refer to the application here https://github.com/PaddlePaddle/PaddleVideo/tree/72c5b40d3415b34cdf50f2848a230d983dc0f7ae/applications
