### ISSUE TITLE
'utf-8' codec can't decode

### ISSUE THREAD

**Issue by nasaweimao** [PaddlePaddle/PaddleVideo#75]
你好，当我执行示例python videotag_test.py这个脚本的时候，老是报错：UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 43: invalid start byte

**Comment by chajchaj** [comment]
您的问题我们已经收到，研发人员会尽快跟进、回复~

**Comment by nasaweimao** [comment]
Namespace(extractor_config='configs/tsn.yaml', extractor_name='TSN', extractor_weights='weights/tsn', filelist='./data/mp4/1.mp4', label_file='label_3396.txt', predictor_config='configs/attention_lstm.yaml', predictor_name='AttentionLSTM', predictor_weights='weights/attention_lstm', save_dir='data/VideoTag_results', use_gpu=False)
[INFO: videotag_test.py:  232]: Namespace(extractor_config='configs/tsn.yaml', extractor_name='TSN', extractor_weights='weights/tsn', filelist='./data/mp4/1.mp4', label_file='label_3396.txt', predictor_config='configs/attention_lstm.yaml', predictor_name='AttentionLSTM', predictor_weights='weights/attention_lstm', save_dir='data/VideoTag_results', use_gpu=False)
[INFO: videotag_test.py:  128]: load extractor weights from weights/tsn
[INFO: tsn.py:  154]: Load pretrain weights from weights/tsn, exclude fc layer.
===pretrain=== weights/tsn
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/maowei/anaconda3/envs/paddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/maowei/anaconda3/envs/paddle/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/maowei/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/reader/decorator.py", line 405, in order_read_worker
    for i in reader():
  File "/Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/reader/kinetics_reader.py", line 196, in reader_
    lines = [line.strip() for line in flist]
  File "/Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/reader/kinetics_reader.py", line 196, in <listcomp>
    lines = [line.strip() for line in flist]
  File "/Users/maowei/anaconda3/envs/paddle/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 43: invalid start byte

**Comment by huangjun12** [comment]
data/VideoTag_test.list里面用的是中文名嘛 改成英文名试下呢

**Comment by nasaweimao** [comment]
请问老师VideoTag_test.list文件夹里面是什么东西呢？

**Comment by huangjun12** [comment]
> 请问老师VideoTag_test.list文件夹里面是什么东西呢？

待预测的视频文件的路径列表

**Comment by nasaweimao** [comment]
老师我按照你说的。python videotag_test.py
Namespace(extractor_config='configs/tsn.yaml', extractor_name='TSN', extractor_weights='weights/tsn', filelist='/Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/data/VideoTag_test.list', label_file='label_3396.txt', predictor_config='configs/attention_lstm.yaml', predictor_name='AttentionLSTM', predictor_weights='weights/attention_lstm', save_dir='data/testlist.txt', use_gpu=False)
[INFO: videotag_test.py:  232]: Namespace(extractor_config='configs/tsn.yaml', extractor_name='TSN', extractor_weights='weights/tsn', filelist='/Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/data/VideoTag_test.list', label_file='label_3396.txt', predictor_config='configs/attention_lstm.yaml', predictor_name='AttentionLSTM', predictor_weights='weights/attention_lstm', save_dir='data/testlist.txt', use_gpu=False)
[INFO: videotag_test.py:  128]: load extractor weights from weights/tsn
[INFO: tsn.py:  154]: Load pretrain weights from weights/tsn, exclude fc layer.
===pretrain=== weights/tsn
Traceback (most recent call last):
  File "videotag_test.py", line 233, in <module>
    main()
  File "videotag_test.py", line 136, in main
    extractor_infer_config)
  File "/Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/reader/reader_utils.py", line 80, in get_reader
    return reader_model.create_reader()
  File "/Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/reader/kinetics_reader.py", line 111, in create_reader
    '{} not exist, please check the data list'.format(self.filelist)
AssertionError: /Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/data/VideoTag_test.list not exist, please check the data list
老师提示list不存在

**Comment by wgh1989** [comment]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 43: invalid start byte
这个是编码问题，一般在文件open的时候加上encoding='utf-8'即可
或者直接export LANG="en_US.UTF-8"
