### ISSUE TITLE
PaddleVideo类的predict函数的输入为文件夹时会报错

### ISSUE THREAD

**Issue by mohui37** [PaddlePaddle/PaddleVideo#76]
**Describe the bug**
PaddleVideo类的predict函数的输入为文件夹时会报错

**To Reproduce**
from ppvideo import PaddleVideo
clas = PaddleVideo(model_name='ppTSM',use_gpu=False,use_tensorrt=False)
video_file='/root/root/ppvideo_tool/video/'
result=clas.predict(video_file)
print(result)

因为源码中这里出错了：
/opt/conda/lib/python3.6/site-packages/ppvideo/tools/paddlevideo_clas.py
293行起：
        for filename in video_list:
            print(filename)
            if isinstance(filename, str):
                #v = utils.decode(video, self.args)  #原代码
                v = utils.decode(filename, self.args)  #我认为的正确代码

**Screenshots**
![issue1](https://user-images.githubusercontent.com/77723348/105153557-8bb89b80-5b43-11eb-89db-f9e8fea795a8.png)
![issue2](https://user-images.githubusercontent.com/77723348/105153575-9115e600-5b43-11eb-854c-243e1d6e264b.png)

**Comment by huangjun12** [comment]
好的， 可以提个pr哈~

**Comment by mohui37** [comment]
> 好的， 可以提个pr哈~

提了提了

**Comment by huangjun12** [comment]
fixed in #82
