### ISSUE TITLE
VideoTag_test.list not exist

### ISSUE THREAD

**Issue by nasaweimao** [PaddlePaddle/PaddleVideo#77]
你好，我在怕video-tag的demo的时候执行python videotag_test.py
系统老是说
Namespace(extractor_config='configs/tsn.yaml', extractor_name='TSN', extractor_weights='weights/tsn', filelist='/Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/data/VideoTag_test.list', label_file='label_3396.txt', predictor_config='configs/attention_lstm.yaml', predictor_name='AttentionLSTM', predictor_weights='weights/attention_lstm', save_dir='data/testlist.txt', use_gpu=False)
[INFO: videotag_test.py:  232]: Namespace(extractor_config='configs/tsn.yaml', extractor_name='TSN', extractor_weights='weights/tsn', filelist='/Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/data/VideoTag_test.list', label_file='label_3396.txt', predictor_config='configs/attention_lstm.yaml', predictor_name='AttentionLSTM', predictor_weights='weights/attention_lstm', save_dir='data/testlist.txt', use_gpu=False)
[INFO: videotag_test.py:  128]: load extractor weights from weights/tsn
[INFO: tsn.py:  154]: Load pretrain weights from weights/tsn, exclude fc layer.
===pretrain=== weights/tsn
Traceback (most recent call last):
  File "videotag_test.py", line 233, in <module>
    main()
  File "videotag_test.py", line 136, in main
    extractor_infer_config)
  File "/Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/reader/reader_utils.py", line 80, in get_reader
    return reader_model.create_reader()
  File "/Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/reader/kinetics_reader.py", line 111, in create_reader
    '{} not exist, please check the data list'.format(self.filelist)
AssertionError: /Users/maowei/Desktop/work/PaddleVideo-application/VideoTag/data/VideoTag_test.list not exist, please check the data list。
list的文件不存在，实际上list文件有的呢

**Comment by chajchaj** [comment]
您的问题我们已经收到，研发人员会尽快跟进、回复~

**Comment by nasaweimao** [comment]
已经解决

**Comment by huangjun12** [comment]
已更新~ 修复pr  #83
