### ISSUE TITLE
请问足球事件分类数据集会开源嘛

### ISSUE THREAD

**Issue by PotentialX** [PaddlePaddle/PaddleVideo#79]
请问足球时间分类数据集会开源嘛，辛苦各位paddle开发者了

**Comment by chajchaj** [comment]
可以

**Comment by huangjun12** [comment]
已开源，下载链接参考 https://github.com/PaddlePaddle/PaddleVideo/blob/application/FootballAction/datasets/EuroCup2016/dataset_url.list
