### ISSUE TITLE
k400数据集无法使用

### ISSUE THREAD

**Issue by jsnt-fym** [PaddlePaddle/PaddleVideo#80]

**Comment by chajchaj** [comment]
麻烦提供一下问题具体信息~

**Comment by jsnt-fym** [comment]
> 麻烦提供一下问题具体信息~

![微信截图_20210120211005](https://user-images.githubusercontent.com/39521118/105179180-f548a200-5b63-11eb-9694-21ca19759bd2.png)
打开链接是404

**Comment by jsnt-fym** [comment]
> 麻烦提供一下问题具体信息~

tsn模型里 K400数据准备 这个链接打开是404

**Comment by chajchaj** [comment]
感谢，我们尽快修复~
