### ISSUE TITLE
aistudio安装ffmpeg

### ISSUE THREAD

**Issue by mtz1992** [PaddlePaddle/PaddleVideo#88]
我看到footballaction的准备环境中需要ffmpeg，请问AIstudio能安装ffmpeg吗？我这安装时报错没权限

**Comment by linhandev** [comment]
studio没有sudo不能装东西，但是石油ffmpeg的
![image](https://user-images.githubusercontent.com/29757093/105577452-b198a700-5db4-11eb-8197-699269e32673.png)

**Comment by lxk767363331** [comment]
出于安全因素考虑，AI Studio暂未开放sudo权限，短期来看，您可以通过源码编译的方式安装，可参考：https://aistudio.baidu.com/aistudio/projectdetail/1463208?channelType=0&channel=0
您的这个安装包，我们后期将根据用户需求考虑为您在环境中预装，欢迎随时邮件AI Studio
