### ISSUE TITLE
预测自己视频的时候，内存会爆

### ISSUE THREAD

**Issue by hualitlc** [PaddlePaddle/PaddleVideo#90]
预测5个视频，每个3-5分钟以内，会占用内存到爆

**Comment by hualitlc** [comment]
执行 videotag_test.py 的时候

**Comment by huangjun12** [comment]
videotag_test.py现在的实现方式，是把所有数据特征提取完之后，再输入到lstm做分类，而不是一条处理完再处理另外一条，所以占用的内存会比较大。建议把3-5分钟的视频截取一下，后面我们也会优化这种实现

**Comment by ranjiewwen** [comment]
> videotag_test.py现在的实现方式，是把所有数据特征提取完之后，再输入到lstm做分类，而不是一条处理完再处理另外一条，所以占用的内存会比较大。建议把3-5分钟的视频截取一下，后面我们也会优化这种实现

跑tsn提特征也会OOM呀？比较多的小视频批量提取

**Comment by Skye2099** [comment]
> > videotag_test.py现在的实现方式，是把所有数据特征提取完之后，再输入到lstm做分类，而不是一条处理完再处理另外一条，所以占用的内存会比较大。建议把3-5分钟的视频截取一下，后面我们也会优化这种实现
> 
> 跑tsn提特征也会OOM呀？比较多的小视频批量提取

我也是，只tsn提特征也会爆，请问你解决了吗

**Comment by ranjiewwen** [comment]
@Skye2099 把时间超过多少的长视频去掉；有可能短视频里面夹杂稍微长点的视频
