### ISSUE TITLE
Can't join wechat group with over 200 members without invitation

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleVideo#91]
微信群过200人了， 需要邀请才能进。希望能提供个方便加群的方式

**Comment by grasswolfs** [comment]
![image](https://user-images.githubusercontent.com/23690325/105792588-a4e99e00-5fc2-11eb-913b-abab78e027cf.png)
更新了一下二维码，添加运营同学，回复“视频”就可以邀请进去了哈，实在抱歉，现在确实也没有更好办法了

**Comment by linhandev** [comment]
没事，这方法就挺好了，微信大群基本都这么干。十分感谢！
