### ISSUE TITLE
生成pkl文件后如何解析

### ISSUE THREAD

**Issue by YongdongTan** [PaddlePaddle/PaddleVideo#93]
您好，我使用get_instance_for_tsn.py生成了pkl文件，请问我如何将这些文件里面包含的图片信息解析为opencv或Image可处理的格式。

**Comment by wgh1989** [comment]
可以参考TSN的官方训练代码
`
def imageloader(buf):
    if isinstance(buf, str):
        img = Image.open(StringIO(buf))
    else:
        img = Image.open(BytesIO(buf))
    return img.convert('RGB')
`

**Comment by wgh1989** [comment]
可以参考TSN的官方训练代码
![image](https://user-images.githubusercontent.com/35423940/105821058-5bff0d00-5ff5-11eb-9810-a4c7af61bb5e.png)
