### ISSUE TITLE
能举个例子说明video tag项目训练attention lstm多标签怎么标注吗？

### ISSUE THREAD

**Issue by wangxinzhe0617** [PaddlePaddle/PaddleVideo#99]
项目中只是说了使用多标签微调lstm 没有说明具体该怎么给视频标注多标签 标注几个 这个对于新手也比较难，能举个例子说明一下嘛，给没有经验的小菜一个标注的方向，万分感谢！谢谢！

**Comment by huangjun12** [comment]
https://github.com/PaddlePaddle/PaddleVideo/blob/application/VideoTag/FineTune.md#数据准备-1  这部分文档对你的问题是否有帮助呢

**Comment by wangxinzhe0617** [comment]
> [https://github.com/PaddlePaddle/PaddleVideo/blob/application/VideoTag/FineTune.md#数据准备-1](https://github.com/PaddlePaddle/PaddleVideo/blob/application/VideoTag/FineTune.md#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87-1) 这部分文档对你的问题是否有帮助呢

非常感谢您的回答！这个我知道 主要是不知道视频标签具体到哪种程度  需要是语义标签+实体标签  还是说只需要标语义标签就行  看三千多分类里有语义标签美女，还有特别具体的标签比如 大长腿     是不是说有个小姐姐跳舞的视频就标为  美女 跳舞 大长腿？三个标签？ 类似的还有语义标签宠物 具体的有熊猫  还有一些很奇怪的标签 比如胶合板，横梁。。。不知道这是根据什么定义的？

**Comment by chajchaj** [comment]
3k分类标签的整体构建策略时：机器挖掘+部分人工review。
人工review时参考了youtube-8m数据集论文的部分策略，比如考虑了标签是否视觉可分，进行无意义标签删除。
具体的挖掘策略 @huangjun12 大佬补充。

**Comment by huangjun12** [comment]
这些标签是根据业务线上热门query得到的，包括语义标签和实体标签，训练的时候所有标签都打平了，没有层级关系

**Comment by wangxinzhe0617** [comment]
> 3k分类标签的整体构建策略是：机器挖掘+部分人工review。
> 人工review时参考了youtube-8m数据集论文的部分策略，比如考虑了标签是否视觉可分，进行无意义标签删除。
> 具体的挖掘策略 @huangjun12 大佬补充。

谢大佬回答 那就是每个视频需要打上语义标签+实体标签（也就是可视化的标签）？ 有数量要求么？希望大佬能给个栗子！就是给出一个视频 然后训练lstm的标签这样 谢谢 ！

**Comment by wangxinzhe0617** [comment]
> 这些标签是根据业务线上热门query得到的，包括语义标签和实体标签，训练的时候所有标签都打平了，没有层级关系

大佬，机器挖掘具体用的是神马策略 方便透漏吗？ @ @
                                                                                     --

**Comment by chajchaj** [comment]
> 
> 
> > 3k分类标签的整体构建策略是：机器挖掘+部分人工review。
> > 人工review时参考了youtube-8m数据集论文的部分策略，比如考虑了标签是否视觉可分，进行无意义标签删除。
> > 具体的挖掘策略 @huangjun12 大佬补充。
> 
> 谢大佬回答 那就是每个视频需要打上语义标签+实体标签（也就是可视化的标签）？ 有数量要求么？希望大佬能给个栗子！就是给出一个视频 然后训练lstm的标签这样 谢谢 ！

几点建议（from https://research.google.com/youtube8m/）：
    Each video must be public and have at least 1000 views
    Each video must be between 120 and 500 seconds long
    Each video must be associated with at least one entity from our target vocabulary
    Adult & sensitive content is removed (as determined by automated classifiers)

**Comment by wangxinzhe0617** [comment]
> > > 3k分类标签的整体构建策略是：机器挖掘+部分人工review。
> > > 人工review时参考了youtube-8m数据集论文的部分策略，比如考虑了标签是否视觉可分，进行无意义标签删除。
> > > 具体的挖掘策略 @huangjun12 大佬补充。
> > 
> > 
> > 谢大佬回答 那就是每个视频需要打上语义标签+实体标签（也就是可视化的标签）？ 有数量要求么？希望大佬能给个栗子！就是给出一个视频 然后训练lstm的标签这样 谢谢 ！
> 
> 几点建议（from [https://research.google.com/youtube8m/）：](https://research.google.com/youtube8m/%EF%BC%89%EF%BC%9A)
> Each video must be public and have at least 1000 views
> Each video must be between 120 and 500 seconds long
> Each video must be associated with at least one entity from our target vocabulary
> Adult & sensitive content is removed (as determined by automated classifiers)



> > > 3k分类标签的整体构建策略是：机器挖掘+部分人工review。
> > > 人工review时参考了youtube-8m数据集论文的部分策略，比如考虑了标签是否视觉可分，进行无意义标签删除。
> > > 具体的挖掘策略 @huangjun12 大佬补充。
> > 
> > 
> > 谢大佬回答 那就是每个视频需要打上语义标签+实体标签（也就是可视化的标签）？ 有数量要求么？希望大佬能给个栗子！就是给出一个视频 然后训练lstm的标签这样 谢谢 ！
> 
> 几点建议（from [https://research.google.com/youtube8m/）：](https://research.google.com/youtube8m/%EF%BC%89%EF%BC%9A)
> Each video must be public and have at least 1000 views
> Each video must be between 120 and 500 seconds long
> Each video must be associated with at least one entity from our target vocabulary
> Adult & sensitive content is removed (as determined by automated classifiers)

非常感谢！

**Comment by chajchaj** [comment]
虽然，我们公司业务相关的策略不方便透露。
但是，建议参考：https://arxiv.org/pdf/1609.08675.pdf

**Comment by chajchaj** [comment]
> 
> 
> > 这些标签是根据业务线上热门query得到的，包括语义标签和实体标签，训练的时候所有标签都打平了，没有层级关系
> 
> 大佬，机器挖掘具体用的是神马策略 方便透漏吗？ @ @
> --

虽然，我们公司业务相关的策略不方便透露。
但是，建议参考：https://arxiv.org/pdf/1609.08675.pdf

**Comment by wangxinzhe0617** [comment]
> > > 这些标签是根据业务线上热门query得到的，包括语义标签和实体标签，训练的时候所有标签都打平了，没有层级关系
> > 
> > 
> > ## 大佬，机器挖掘具体用的是神马策略 方便透漏吗？ @ @
> 
> 虽然，我们公司业务相关的策略不方便透露。
> 但是，建议参考：https://arxiv.org/pdf/1609.08675.pdf

好的谢谢大佬
